builds:
  - binary: go-travis-wait
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archive:
  files:
    - none*

release:
  github:
    owner: chanzuckerberg
    name: go-travis-wait
